name: connacta
description: A messaging and photo shearing application with flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  firebase_messaging: ^6.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: any

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: barlow
      fonts:
        - asset: assets/fonts/barlow_extra_bold.ttf

